package fr.epistudio.epysia.editor.icons;

public enum EditorIcon {
    EPYSIA_LOGO("EpysiaLogo"),
    PARTICLES_3D("GPUParticles3D"),
    SPRITE_2D("Sprite2D"),
    TILE_MAP("TileMap"),
    NODE_2D("Node2D"),
    CONTROL("Control"),
    NAVIGATION_AGENT_3D("NavigationAgent3D"),
    NAVIGATION_REGION_3D("NavigationRegion3D"),
    REMOTE_TRANSFORM_3D("RemoteTransform3D"),
    WORLD_ENVIRONMENT("WorldEnvironment"),
    LABEL_3D("Label3D"),
    FOG_VOLUME("FogVolume"),
    LIGHTMAP_PROBE("LightmapProbe"),
    HINGE_JOINT_3D("HingeJoint3D"),
    AUDIO_LISTENER_3D("AudioListener3D"),
    AUDIO_STREAM_PLAYER_3D("AudioStreamPlayer3D"),
    CHARACTER_BODY_2D("CharacterBody2D"),
    RIGID_BODY_2D("RigidBody2D"),
    POINT_LIGHT_2D("PointLight2D"),
    COLLISION_SHAPE_2D("CollisionShape2D"),
    ANIMATED_SPRITE_2D("AnimatedSprite2D"),
    AUDIO_MICROPHONE("AudioStreamMicrophone"),
    DECAL("Decal"),
    ACTION_COPY("ActionCopy"),
    ACTION_PASTE("ActionPaste"),
    ADD("Add"),
    ANIMATION("Animation"),
    ATLAS_TEXTURE("AtlasTexture"),
    AUDIO_STREAM("AudioStream"),
    GRAPH_EDIT("GraphEdit"),
    PACKED_SCENE("PackedScene"),
    SHADER("Shader"),
    STANDARD_MATERIAL("StandardMaterial3D"),
    TEXTURE_2D("Texture2D"),
    BUCKET("Bucket"),
    CANVAS_LAYER("CanvasLayer"),
    ANIMATION_PLAYER("AnimationPlayer"),
    CAMERA_3D("Camera3D"),
    CHARACTER_BODY_3D("CharacterBody3D"),
    COLLISION_SHAPE_3D("CollisionShape3D"),
    DIRECTIONAL_LIGHT_3D("DirectionalLight3D"),
    COLOR_PICK("ColorPick"),
    DUPLICATE("Duplicate"),
    EDIT("Edit"),
    ERASER("Eraser"),
    FILE("File"),
    FOLDER("Folder"),
    GRID("Grid"),
    VISIBILITY_HIDDEN("GuiVisibilityHidden"),
    VISIBILITY_VISIBLE("GuiVisibilityVisible"),
    LINE("Line"),
    LOAD("Load"),
    LOCK("Lock"),
    MESH("Mesh"),
    MESH_INSTANCE_3D("MeshInstance3D"),
    NODE_3D("Node3D"),
    OMNI_LIGHT_3D("OmniLight3D"),
    PAUSE("Pause"),
    PLAY("Play"),
    REDO("Redo"),
    REMOVE("Remove"),
    RIGID_BODY_3D("RigidBody3D"),
    SAVE("Save"),
    SCRIPT("Script"),
    RECTANGLE("Rectangle"),
    SNAP("Snap"),
    SPOT_LIGHT_3D("SpotLight3D"),
    STATIC_BODY_3D("StaticBody3D"),
    STOP("Stop"),
    TERRAIN_CONNECT("TerrainConnect"),
    TERRAIN_MATCH_CORNERS("TerrainMatchCorners"),
    TERRAIN_MATCH_CORNERS_AND_SIDES("TerrainMatchCornersAndSides"),
    TERRAIN_MATCH_SIDES("TerrainMatchSides"),
    TOOL_MOVE("ToolMove"),
    TOOL_PIVOT("ToolPivot"),
    TOOL_ROTATE("ToolRotate"),
    TOOL_SCALE("ToolScale"),
    TOOL_SELECT("ToolSelect"),
    UNLOCK("Unlock");

    private final String fileName;

    EditorIcon(String fileName) {
        this.fileName = fileName;
    }

    public String resourcePath() {
        return "/editor/icons/png/" + fileName + ".png";
    }
}
